name: Build Executables

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release Name (e.g., OpenSpeedrunConverter v1.0.0)'
        required: true
        default: 'OpenSpeedrunConverter v1.0.0'
      prerelease:
        description: 'Is this a pre-release?'
        required: true
        type: boolean
        default: false

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed main.py
    - name: Rename Linux executable
      run: mv dist/main dist/openspeedrunconverter-linux
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: openspeedrunconverter-linux
        path: dist/openspeedrunconverter-linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed main.py
    - name: Rename Windows executable
      run: mv dist/main.exe dist/openspeedrunconverter-windows.exe
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: openspeedrunconverter-windows
        path: dist/openspeedrunconverter-windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed main.py
    - name: Rename macOS executable
      run: mv dist/main dist/openspeedrunconverter-macos
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: openspeedrunconverter-macos
        path: dist/openspeedrunconverter-macos

  create-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    if: true # Always run when manually dispatched
    steps:
    - uses: actions/checkout@v4
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: List downloaded artifacts
      run: ls -R artifacts
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/openspeedrunconverter-linux/openspeedrunconverter-linux
          artifacts/openspeedrunconverter-windows/openspeedrunconverter-windows.exe
          artifacts/openspeedrunconverter-macos/openspeedrunconverter-macos
        name: ${{ github.event.inputs.release_name }}
        tag_name: ${{ github.event.inputs.release_tag }}
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
