name: Build Executables

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed main.py
    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: openspeedrunconverter-linux
        path: dist/main

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed main.py
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: openspeedrunconverter-windows
        path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed main.py
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: openspeedrunconverter-macos
        path: dist/main
